"""
Constants file
"""
NEWGAMELIVES = 3
SQUAREDIM = 80
FPS = 60
BOMBERSPEED = 30
BOMBERMOVERATE = 0.3
BOMBDROPRATE = 0.5
BOMBTIME = FPS*3
ANGRYSPEED = 10
STAGESDIR = "maps/"
STAGESLIST = [ "mapa1.txt",
        "mapa2.txt",
        "mapa3.txt",
        "mapa4.txt"]
SCREENWIDTH = 800
SCREENHEIGHT = 450
CAPTION = "Duck Kogs"
IMAGESDIR = "img/"
LEFTPANELIMG = IMAGESDIR + "leftPanel.png"
CENTRALPANELIMG = IMAGESDIR + "centralPanel.png"
RIGHTPANELIMG = IMAGESDIR + "rightPanel.png"
LEFTPANELPOS = (0, 0)
CENTRALPANELPOS = (SCREENWIDTH*0.1, 0)
RIGHTPANELPOS = (SCREENWIDTH*0.9, 0)
MENUOPTIONSCOUNT = 5
EXPLOSIONCENTER = -1
EXPLOSIONTIME = FPS*1
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3
STUNTIME = FPS*3
